[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

# [tool.pytest.ini_options]
# pythonpath = ["."]
# addopts = "--ignore=path"

[tool.pyright]
executionEnvironments = [{ root = "src" }]
typeCheckingMode = "standard"
venv = ".venv"
venvPath = "."

